/**
 * Fetch the project publish index from .pipeline/publishes.json.
 * The index is generated by python/pipeline/indexer.py and served as a static file.
 */
import { useState, useEffect, useCallback } from 'react'

const INDEX_BASE = import.meta.env.VITE_INDEX_BASE ?? ''

async function fetchIndex(projectFolder) {
  const url = projectFolder
    ? `${INDEX_BASE}/${projectFolder}/.pipeline/publishes.json`
    : `${INDEX_BASE}/publishes.json`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status} — ${url}`)
  return res.json()
}

export function usePublishes(projectFolder) {
  const [state, setState] = useState({
    publishes: [],
    projects: [],
    loading: true,
    error: null,
  })

  const load = useCallback(async () => {
    setState(s => ({ ...s, loading: true, error: null }))
    try {
      const data = await fetchIndex(projectFolder)
      setState({
        publishes: data.publishes ?? [],
        projects: data.projects ?? [],
        loading: false,
        error: null,
      })
    } catch (e) {
      setState(s => ({ ...s, loading: false, error: e.message }))
    }
  }, [projectFolder])

  useEffect(() => { load() }, [load])

  return { ...state, refresh: load }
}
